export const enTools = {
	fitInvalid: 'Enter a positive measurement. Clearance may be zero.',
	units: 'Units', imperial: 'Imperial (in / ft)', metric: 'Metric (cm / m)', copy: 'Copy setup link', copied: 'Setup link copied.', manual: 'Copy this link manually:', invalid: 'Enter a valid measurement within the displayed range.',
	view: 'Comparison view', side: 'Side by side', overlay: 'Overlay', alignment: 'Alignment', center: 'Center', bottom: 'Bottom', solid: 'solid outline', dashed: 'dashed outline',
	fitTitle: 'Will it fit?', fitIntro: 'Check a TV against the space you have, with room for clearance on every side.', checkFit: 'Check fit',
	mode: 'Dimension source', estimate: 'Screen estimate', exact: 'Exact TV dimensions',
	estimateNote: 'Screen estimates use 16:9 geometry and exclude the bezel and stand. Exact mode uses the dimensions you supply.',
	exactNote: 'Enter the manufacturer’s width and height. Include the stand in the height if you will use it.',
	width: 'Available width', height: 'Available height (optional)', diagonal: 'TV diagonal (inches)', clearance: 'Clearance on each side', tvWidth: 'Manufacturer width', tvHeight: 'Manufacturer height',
	guidance: 'This checks front-facing dimensions. Check cabinet depth, stand footprint, and the manufacturer’s ventilation requirements separately.',
	blank: 'Enter your available width to check fit.', fits: 'Fits within the entered space', noFit: 'Does not fit within the entered space', widthOnly: 'Width-only check — height has not been checked.', fullCheck: 'Width and height checked.', largest: 'Largest screen estimate', none: 'No supported screen size fits.',
	horizontal: 'Total horizontal space remaining', vertical: 'Total vertical space remaining', overflowX: 'Horizontal overflow', overflowY: 'Vertical overflow', space: 'Available space', television: 'TV', clearanceLegend: 'TV plus clearance (dashed)', dimensions: 'TV width × height',
	fromTv: '{unit} from the TV', simulation: '{size} in TV · {distance} {unit} · {fov}° field of view. {message}', featureTitle: 'Fit, compare, and share', featureText: 'Overlay screens, check your available space, switch units, and copy a link to your setup.',
};
type ToolTranslation = { [K in keyof typeof enTools]: string };
export const esTools = {
	fitInvalid: 'Introduce una medida positiva. El margen puede ser cero.',
	units: 'Unidades', imperial: 'Imperiales (in / ft)', metric: 'Métricas (cm / m)', copy: 'Copiar enlace de configuración', copied: 'Enlace copiado.', manual: 'Copia este enlace manualmente:', invalid: 'Introduce una medida válida dentro del intervalo indicado.',
	view: 'Vista de comparación', side: 'Una al lado de otra', overlay: 'Superposición', alignment: 'Alineación', center: 'Centro', bottom: 'Abajo', solid: 'contorno continuo', dashed: 'contorno discontinuo',
	fitTitle: '¿Cabe?', fitIntro: 'Comprueba si el televisor cabe en tu espacio, dejando un margen en cada lado.', checkFit: 'Comprobar si cabe', mode: 'Origen de las dimensiones', estimate: 'Estimación de pantalla', exact: 'Dimensiones exactas del TV',
	estimateNote: 'Las estimaciones usan la geometría 16:9 y excluyen el marco y el soporte. El modo exacto usa las medidas que introduces.', exactNote: 'Introduce la anchura y altura del fabricante. Incluye el soporte en la altura si lo vas a usar.',
	width: 'Anchura disponible', height: 'Altura disponible (opcional)', diagonal: 'Diagonal del TV (pulgadas)', clearance: 'Margen en cada lado', tvWidth: 'Anchura del fabricante', tvHeight: 'Altura del fabricante', guidance: 'Se comprueban las dimensiones frontales. Revisa por separado la profundidad del mueble, la base del soporte y la ventilación exigida por el fabricante.',
	blank: 'Introduce la anchura disponible para comprobar si cabe.', fits: 'Cabe en el espacio indicado', noFit: 'No cabe en el espacio indicado', widthOnly: 'Solo se comprueba la anchura; no se ha comprobado la altura.', fullCheck: 'Anchura y altura comprobadas.', largest: 'Mayor pantalla estimada', none: 'No cabe ningún tamaño de pantalla de la lista.', horizontal: 'Espacio horizontal total restante', vertical: 'Espacio vertical total restante', overflowX: 'Exceso horizontal', overflowY: 'Exceso vertical', space: 'Espacio disponible', television: 'TV', clearanceLegend: 'TV con margen (discontinuo)', dimensions: 'Anchura × altura del TV', fromTv: '{unit} del televisor', simulation: 'TV de {size} in · {distance} {unit} · campo de visión de {fov}°. {message}', featureTitle: 'Comprueba, compara y comparte', featureText: 'Superpón pantallas, comprueba tu espacio, cambia de unidades y copia un enlace a tu configuración.',
} satisfies ToolTranslation;
export const deTools = {
	fitInvalid: 'Gib einen positiven Messwert ein. Der Freiraum darf null sein.',
	units: 'Einheiten', imperial: 'Imperial (in / ft)', metric: 'Metrisch (cm / m)', copy: 'Link zur Konfiguration kopieren', copied: 'Link kopiert.', manual: 'Diesen Link manuell kopieren:', invalid: 'Gib einen gültigen Messwert im angezeigten Bereich ein.',
	view: 'Vergleichsansicht', side: 'Nebeneinander', overlay: 'Überlagert', alignment: 'Ausrichtung', center: 'Mittig', bottom: 'Unten', solid: 'durchgezogene Kontur', dashed: 'gestrichelte Kontur', fitTitle: 'Passt der Fernseher?', fitIntro: 'Prüfe, ob der Fernseher in deinen Platz passt, mit Freiraum auf jeder Seite.', checkFit: 'Passform prüfen', mode: 'Quelle der Maße', estimate: 'Bildschirmschätzung', exact: 'Exakte TV-Maße', estimateNote: 'Bildschirmschätzungen basieren auf 16:9 und berücksichtigen weder Rahmen noch Standfuß. Der exakte Modus verwendet deine Maße.', exactNote: 'Gib Breite und Höhe laut Hersteller ein. Rechne den Standfuß zur Höhe hinzu, wenn du ihn verwendest.',
	width: 'Verfügbare Breite', height: 'Verfügbare Höhe (optional)', diagonal: 'TV-Diagonale (Zoll)', clearance: 'Freiraum auf jeder Seite', tvWidth: 'Breite laut Hersteller', tvHeight: 'Höhe laut Hersteller', guidance: 'Hier werden die Frontmaße geprüft. Prüfe Schranktiefe, Standfläche und die Lüftungsvorgaben des Herstellers separat.', blank: 'Gib die verfügbare Breite ein.', fits: 'Passt in den angegebenen Platz', noFit: 'Passt nicht in den angegebenen Platz', widthOnly: 'Nur die Breite geprüft — die Höhe wurde nicht geprüft.', fullCheck: 'Breite und Höhe geprüft.', largest: 'Größte Bildschirmschätzung', none: 'Keine der unterstützten Bildschirmgrößen passt.', horizontal: 'Verbleibender horizontaler Platz insgesamt', vertical: 'Verbleibender vertikaler Platz insgesamt', overflowX: 'Horizontaler Überstand', overflowY: 'Vertikaler Überstand', space: 'Verfügbarer Platz', television: 'TV', clearanceLegend: 'TV mit Freiraum (gestrichelt)', dimensions: 'TV-Breite × Höhe', fromTv: '{unit} vom Fernseher entfernt', simulation: '{size} in TV · {distance} {unit} · {fov}° Sichtfeld. {message}', featureTitle: 'Prüfen, vergleichen und teilen', featureText: 'Überlagere Bildschirme, prüfe deinen Platz, wechsle die Einheiten und kopiere einen Link zu deiner Konfiguration.',
} satisfies ToolTranslation;
export const frTools = {
	fitInvalid: 'Saisissez une mesure positive. La marge peut être nulle.',
	units: 'Unités', imperial: 'Impériales (in / ft)', metric: 'Métriques (cm / m)', copy: 'Copier le lien de configuration', copied: 'Lien copié.', manual: 'Copiez ce lien manuellement :', invalid: 'Saisissez une mesure valide dans la plage indiquée.',
	view: 'Vue de comparaison', side: 'Côte à côte', overlay: 'Superposition', alignment: 'Alignement', center: 'Centre', bottom: 'Bas', solid: 'contour continu', dashed: 'contour en pointillés', fitTitle: 'Est-ce que le TV rentre ?', fitIntro: 'Vérifiez si le téléviseur rentre dans votre espace, avec une marge de chaque côté.', checkFit: 'Vérifier les dimensions', mode: 'Source des dimensions', estimate: 'Estimation de l’écran', exact: 'Dimensions exactes du TV', estimateNote: 'Les estimations utilisent la géométrie 16:9, sans cadre ni pied. Le mode exact utilise les dimensions que vous indiquez.', exactNote: 'Saisissez la largeur et la hauteur du fabricant. Incluez le pied dans la hauteur si vous l’utilisez.',
	width: 'Largeur disponible', height: 'Hauteur disponible (facultative)', diagonal: 'Diagonale du TV (pouces)', clearance: 'Marge de chaque côté', tvWidth: 'Largeur du fabricant', tvHeight: 'Hauteur du fabricant', guidance: 'Seules les dimensions de face sont vérifiées. Vérifiez séparément la profondeur du meuble, l’emprise du pied et les exigences de ventilation du fabricant.', blank: 'Saisissez la largeur disponible pour vérifier.', fits: 'Rentre dans l’espace indiqué', noFit: 'Ne rentre pas dans l’espace indiqué', widthOnly: 'Vérification de la largeur uniquement — hauteur non vérifiée.', fullCheck: 'Largeur et hauteur vérifiées.', largest: 'Plus grand écran estimé', none: 'Aucune taille d’écran de la liste ne rentre.', horizontal: 'Espace horizontal total restant', vertical: 'Espace vertical total restant', overflowX: 'Dépassement horizontal', overflowY: 'Dépassement vertical', space: 'Espace disponible', television: 'TV', clearanceLegend: 'TV avec marge (pointillés)', dimensions: 'Largeur × hauteur du TV', fromTv: '{unit} du téléviseur', simulation: 'TV de {size} in · {distance} {unit} · champ de vision de {fov}°. {message}', featureTitle: 'Vérifiez, comparez et partagez', featureText: 'Superposez des écrans, vérifiez votre espace, changez d’unités et copiez un lien vers votre configuration.',
} satisfies ToolTranslation;
export const jaTools = {
	fitInvalid: '正の数値を入力してください。余白は0でも指定できます。',
	units: '単位', imperial: 'ヤード・ポンド法 (in / ft)', metric: 'メートル法 (cm / m)', copy: '設定リンクをコピー', copied: '設定リンクをコピーしました。', manual: 'このリンクを手動でコピーしてください：', invalid: '表示された範囲内の有効な数値を入力してください。',
	view: '比較表示', side: '横に並べる', overlay: '重ね合わせ', alignment: '配置', center: '中央揃え', bottom: '下揃え', solid: '実線の枠', dashed: '破線の枠', fitTitle: '設置できますか？', fitIntro: '各辺の余白を考慮して、テレビが設置スペースに収まるか確認できます。', checkFit: '設置サイズを確認', mode: '寸法の指定方法', estimate: '画面サイズの推定', exact: 'テレビの正確な寸法', estimateNote: '画面の推定値は16:9比率に基づき、ベゼルとスタンドを含みません。正確な寸法モードでは入力した寸法を使用します。', exactNote: 'メーカー公表の幅と高さを入力してください。スタンドを使用する場合は、その高さも含めてください。',
	width: '設置スペースの幅', height: '設置スペースの高さ（任意）', diagonal: 'テレビの対角サイズ（インチ）', clearance: '各辺の余白', tvWidth: 'メーカー公表の幅', tvHeight: 'メーカー公表の高さ', guidance: '正面から見た寸法のみを確認します。棚の奥行き、スタンドの設置面積、メーカー指定の換気スペースは別途確認してください。', blank: '設置スペースの幅を入力してください。', fits: '入力したスペースに収まります', noFit: '入力したスペースに収まりません', widthOnly: '幅のみの確認です。高さは確認していません。', fullCheck: '幅と高さを確認しました。', largest: '設置可能な最大画面サイズの推定', none: '対応する画面サイズで収まるものはありません。', horizontal: '左右の残りスペースの合計', vertical: '上下の残りスペースの合計', overflowX: '横方向の超過', overflowY: '縦方向の超過', space: '設置スペース', television: 'テレビ', clearanceLegend: 'テレビ＋余白（破線）', dimensions: 'テレビの幅 × 高さ', fromTv: 'テレビから {unit}', simulation: '{size} in テレビ・距離 {distance} {unit}・視野角 {fov}°。{message}', featureTitle: '設置確認・比較・共有', featureText: '画面を重ねて比較し、設置スペースを確認。単位を切り替えて設定リンクを共有できます。',
} satisfies ToolTranslation;
